[package]
name = "matrix-blog-migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
heck = "0.4.0"
indexmap = { version = "1.9.1", features = ["serde"] }
itertools = "0.10.5"
serde_yaml = "0.9.13"
toml = { version = "0.5.9", features = ["preserve_order"] }
xshell = "0.1"
